= Package generator Documentation
:author: Christophe Cossou
:sectnums:
:toc: left
:toclevels: 4
:encoding: utf-8
:lang: en
:numbered:
:source-language: python
:imagesdir:   doc

== Introduction
The folder *model_package* contain a generic structure for a Python package, with *setup.py* and everything needed for a basic package.

=== Model Package
Each time the package name must be, a generic tag *<my_package>* must be in its place. During package creation, this tag will be replaced with the name chosen for the package.

=== Plugin
Plugin are available. They are extra lines of code only needed when you want a specific feature. For now, only the *ini_file_plugin* is available. It provides functions to read and validate a configuration file (as an .ini file)

As some might not want it, this is optional (flag --ini for the creation script).


== How to use

Just run the script in its directory:
[source, bash]
----
./generate_package_structure.py --name "toto"
----

The package will appear in a *generated* folder. Copy paste everything in it where you want to put your package (in a new Git repository for instance)

For help on the script, type:
[source, bash]
----
./generate_package_structure.py -h
----

== How to add files in the model structure ?

Files in the *model_package* or any *plugin* folder must respect the same overall structure. I.e. for a plugin to add lines to an existing *<my_package>/utils.py* file, you must create the same file, in the same sub-folder, under the plugin structure, then add the extra lines you want to add.

.Generic rules:
* Each file must end with a blanck line (mainly because of plugins, to avoid that the first line of a plugin file to be added to the last line of the original file)

=== For plugins
Plugin folder must respect the same structure as the main *model_package*.

For instance, here is one structure for *model_package*:
[quote]
----
model_package/
├── <my_package>
│   ├── __init__.py
│   ├── utils.py
│   └── version.py
├── README.adoc
├── requirements.txt
└── setup.py
----

Here is the structure of the *ini_file_plugin*:
[quote]
----
ini_file_plugin/
├── <my_package>
│   ├── config.py
│   ├── configspec.ini
│   └── __init__.py
└── requirements.txt
----

.Plugin rules:
* you don't need to add in the plugin structures files that have not changed compared to the model package
* you can only add lines. You can't delete lines from the *model_package* via a plugin
* When adding to a plugin a file that already exist in *model_package*, its lines will be added at the end of the corresponding original file
